#!/usr/bin/env python

import os
import sys

sys.dont_write_bytecode = True

basedir = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, os.path.join(basedir, "src"))

import octoprint
octoprint.main()
